"""initial_schema

Revision ID: 30f34ea96eda
Revises: 
Create Date: 2026-06-14 14:21:07.142127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30f34ea96eda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sa.Enum('STARTER', 'GROWTH', 'ENTERPRISE', name='plantype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('calls_limit_monthly', sa.Integer(), nullable=False),
    sa.Column('calls_used_this_month', sa.Integer(), nullable=False),
    sa.Column('billing_reset_date', sa.Date(), nullable=True),
    sa.Column('gemini_api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openai_api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('groq_api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sarvam_api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('elevenlabs_api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('monthly_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_slug'), 'organization', ['slug'], unique=True)
    op.create_table('borrower',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loan_account_last4', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emi_amount', sa.Float(), nullable=False),
    sa.Column('emi_due_date', sa.Date(), nullable=True),
    sa.Column('overdue_amount', sa.Float(), nullable=False),
    sa.Column('days_past_due', sa.Integer(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_debit_enabled', sa.Boolean(), nullable=False),
    sa.Column('upi_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_call_date', sa.Date(), nullable=True),
    sa.Column('last_call_outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_calls_this_cycle', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrower_org_id'), 'borrower', ['org_id'], unique=False)
    op.create_index(op.f('ix_borrower_phone'), 'borrower', ['phone'], unique=False)
    op.create_table('daily_call_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('connected_calls', sa.Integer(), nullable=False),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=False),
    sa.Column('ptp_count', sa.Integer(), nullable=False),
    sa.Column('payment_confirmed_count', sa.Integer(), nullable=False),
    sa.Column('refused_count', sa.Integer(), nullable=False),
    sa.Column('no_answer_count', sa.Integer(), nullable=False),
    sa.Column('llm_cost_usd', sa.Float(), nullable=False),
    sa.Column('stt_cost_usd', sa.Float(), nullable=False),
    sa.Column('tts_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('avg_first_response_ms', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_call_stats_org_id'), 'daily_call_stats', ['org_id'], unique=False)
    op.create_index(op.f('ix_daily_call_stats_stat_date'), 'daily_call_stats', ['stat_date'], unique=False)
    op.create_table('telephony_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('OZONETEL', 'TWILIO', name='telephonyprovider'), nullable=False),
    sa.Column('api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_password_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twilio_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('did_numbers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=False),
    sa.Column('calls_per_minute_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telephony_config_org_id'), 'telephony_config', ['org_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'ORG_MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_org_id'), 'user', ['org_id'], unique=False)
    op.create_table('voice_agent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examples', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('max_call_turns', sa.Integer(), nullable=False),
    sa.Column('stt_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tts_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_agent_name'), 'voice_agent', ['name'], unique=False)
    op.create_index(op.f('ix_voice_agent_org_id'), 'voice_agent', ['org_id'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('audience_count', sa.Integer(), nullable=False),
    sa.Column('calls_made', sa.Integer(), nullable=False),
    sa.Column('calls_connected', sa.Integer(), nullable=False),
    sa.Column('calls_failed', sa.Integer(), nullable=False),
    sa.Column('schedule_at', sa.DateTime(), nullable=True),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agent.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_agent_id'), 'campaign', ['agent_id'], unique=False)
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_org_id'), 'campaign', ['org_id'], unique=False)
    op.create_index(op.f('ix_campaign_schedule_at'), 'campaign', ['schedule_at'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_table('call_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('borrower_id', sa.Uuid(), nullable=False),
    sa.Column('call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.Enum('PAYMENT_CONFIRMED', 'ALREADY_PAID', 'PAID_ON_CALL', 'PTP_CAPTURED', 'PARTIAL_PAYMENT_AGREED', 'CALLBACK_REQUESTED', 'CANT_PAY', 'DISPUTE_RAISED', 'REFUSED', 'NO_ANSWER', 'WRONG_NUMBER', 'DND_REQUESTED', 'BUSY', 'VOICEMAIL', 'IN_PROGRESS', name='calloutcome'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('ptp_date', sa.Date(), nullable=True),
    sa.Column('ptp_amount', sa.Float(), nullable=True),
    sa.Column('utr_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recording_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_log_borrower_id'), 'call_log', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_call_log_call_sid'), 'call_log', ['call_sid'], unique=True)
    op.create_index(op.f('ix_call_log_campaign_id'), 'call_log', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_call_log_org_id'), 'call_log', ['org_id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('borrower_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('call_log_id', sa.Uuid(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('call_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['voice_agent.id'], ),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_log.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_agent_id'), 'conversation', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversation_borrower_id'), 'conversation', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_conversation_campaign_id'), 'conversation', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_conversation_org_id'), 'conversation', ['org_id'], unique=False)
    op.create_index(op.f('ix_conversation_phone_number'), 'conversation', ['phone_number'], unique=False)
    op.create_table('dnd_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_by_call_log_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_call_log_id'], ['call_log.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dnd_entry_org_id'), 'dnd_entry', ['org_id'], unique=False)
    op.create_index(op.f('ix_dnd_entry_phone'), 'dnd_entry', ['phone'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speech_start_time', sa.Float(), nullable=True),
    sa.Column('speech_end_time', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_org_id'), 'message', ['org_id'], unique=False)
    op.create_index(op.f('ix_message_sender'), 'message', ['sender'], unique=False)
    op.create_table('usage_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('call_log_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('GEMINI', 'OPENAI', 'GROQ', 'SARVAM_STT', 'SARVAM_TTS', 'ELEVENLABS', 'BEDROCK', 'OZONETEL', name='llmprovider'), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('audio_seconds', sa.Float(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_log.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_event_call_log_id'), 'usage_event', ['call_log_id'], unique=False)
    op.create_index(op.f('ix_usage_event_org_id'), 'usage_event', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_event_org_id'), table_name='usage_event')
    op.drop_index(op.f('ix_usage_event_call_log_id'), table_name='usage_event')
    op.drop_table('usage_event')
    op.drop_index(op.f('ix_message_sender'), table_name='message')
    op.drop_index(op.f('ix_message_org_id'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_dnd_entry_phone'), table_name='dnd_entry')
    op.drop_index(op.f('ix_dnd_entry_org_id'), table_name='dnd_entry')
    op.drop_table('dnd_entry')
    op.drop_index(op.f('ix_conversation_phone_number'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_org_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_campaign_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_borrower_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_agent_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_call_log_org_id'), table_name='call_log')
    op.drop_index(op.f('ix_call_log_campaign_id'), table_name='call_log')
    op.drop_index(op.f('ix_call_log_call_sid'), table_name='call_log')
    op.drop_index(op.f('ix_call_log_borrower_id'), table_name='call_log')
    op.drop_table('call_log')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_schedule_at'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_org_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_agent_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_voice_agent_org_id'), table_name='voice_agent')
    op.drop_index(op.f('ix_voice_agent_name'), table_name='voice_agent')
    op.drop_table('voice_agent')
    op.drop_index(op.f('ix_user_org_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_telephony_config_org_id'), table_name='telephony_config')
    op.drop_table('telephony_config')
    op.drop_index(op.f('ix_daily_call_stats_stat_date'), table_name='daily_call_stats')
    op.drop_index(op.f('ix_daily_call_stats_org_id'), table_name='daily_call_stats')
    op.drop_table('daily_call_stats')
    op.drop_index(op.f('ix_borrower_phone'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_org_id'), table_name='borrower')
    op.drop_table('borrower')
    op.drop_index(op.f('ix_organization_slug'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
